### Health check

GET http://my-api.local/api/health
Accept: application/json

### Metrics

GET http://my-api.local/api/metrics
Accept: application/json

### Good Contact request

POST http://my-api.local/api/contact
Content-Type: application/json
Accept: application/json

{
    "name": "София",
    "phone": "+79999999999",
    "email": "Al3xandrShein@yandex.ru",
    "comment": "вы сделали отличный сайт, спасибо!"
}

### Bad Contact request

POST http://my-api.local/api/contact
Content-Type: application/json
Accept: application/json

{
    "name": "",
    "phone": "123",
    "email": "abc",
    "comment": ""
}

### Test 500 Error

GET http://my-api.local/api/test-error
Accept: application/json


### Mail Config

GET http://my-api.local/api/mail-config
Accept: application/json


### SMTP Status

GET http://my-api.local/api/smtp
Accept: application/json


### DNS Test

GET http://my-api.local/api/dns-test
Accept: application/json


### Google Test

GET http://my-api.local/api/google-test
Accept: application/json

### Gmail Test
GET http://my-api.local/api/gmail-test
Accept: application/json

### Resend Test
GET http://my-api.local/api/resend-test
Accept: application/json